`timescale 1ns/1ps
module tb_relay_bp_tier2_n2_one_iteration;
 localparam C=1728,V=67752,E=391320,L=1;logic clk=0,rst=1,start=0,cfg_we=0;logic[3:0]cfg_kind=0;logic[31:0]cfg_addr=0,frame_id=77;logic signed[31:0]cfg_data=0;
 logic sa;logic[31:0]af;logic b0,b1,d0,d1,f0,f1,c0,c1;logic signed[31:0]w0,w1;logic[31:0]it0,it1;logic[0:0]l0,l1;logic gd,gf,gcv,win,sc;logic[31:0]fsc,dc0,dc1;logic correction_ready,correction_rsp_valid;logic[3:0]correction_bits,correction_mask;
 logic signed[17:0]expected_mu[0:E-1],expected_nu[0:E-1],expected_marg[0:V-1];logic expected_dec[0:V-1];integer e,v,fail;
 always #5 clk=~clk;
 relay_bp_parallel_n2_p4 #(.C(C),.V(V),.E(E),.L(L),
  .CP_INIT("fpga/verification/tier2_p0p003/images/check_row_ptr.memh"),.VP_INIT("fpga/verification/tier2_p0p003/images/variable_row_ptr.memh"),
  .EV_B0_INIT("fpga/verification/tier2_p0p003/images/check_edge_fault_ids_b0.memh"),.EV_B1_INIT("fpga/verification/tier2_p0p003/images/check_edge_fault_ids_b1.memh"),.EV_B2_INIT("fpga/verification/tier2_p0p003/images/check_edge_fault_ids_b2.memh"),.EV_B3_INIT("fpga/verification/tier2_p0p003/images/check_edge_fault_ids_b3.memh"),
  .VE_B0_INIT("fpga/verification/tier2_p0p003/images/variable_to_edge_b0.memh"),.VE_B1_INIT("fpga/verification/tier2_p0p003/images/variable_to_edge_b1.memh"),.VE_B2_INIT("fpga/verification/tier2_p0p003/images/variable_to_edge_b2.memh"),.VE_B3_INIT("fpga/verification/tier2_p0p003/images/variable_to_edge_b3.memh"),
  .PRIOR_B0_INIT("fpga/verification/tier2_p0p003/images/priors_b0.memh"),.PRIOR_B1_INIT("fpga/verification/tier2_p0p003/images/priors_b1.memh"),.PRIOR_B2_INIT("fpga/verification/tier2_p0p003/images/priors_b2.memh"),.PRIOR_B3_INIT("fpga/verification/tier2_p0p003/images/priors_b3.memh"),
  .MARG_B0_INIT("fpga/verification/tier2_p0p003/images/priors_b0.memh"),.MARG_B1_INIT("fpga/verification/tier2_p0p003/images/priors_b1.memh"),.MARG_B2_INIT("fpga/verification/tier2_p0p003/images/priors_b2.memh"),.MARG_B3_INIT("fpga/verification/tier2_p0p003/images/priors_b3.memh"),
  .SYN_B0_INIT("fpga/verification/tier2_p0p003/images/syndrome_shot0_b0.memh"),.SYN_B1_INIT("fpga/verification/tier2_p0p003/images/syndrome_shot0_b1.memh"),.SYN_B2_INIT("fpga/verification/tier2_p0p003/images/syndrome_shot0_b2.memh"),.SYN_B3_INIT("fpga/verification/tier2_p0p003/images/syndrome_shot0_b3.memh"))dut(.clk,.rst,.start,.cfg_we,.cfg_kind,.cfg_addr,.cfg_data,.first_limit(16'd1),.later_limit(16'd1),.first_gamma(5'sd2),.frame_id,
  .gamma0_valid(1'b0),.gamma0_variable_index(17'd0),.gamma0_value(5'sd0),.gamma0_done(1'b0),.gamma0_seed_valid(1'b0),.gamma0_seed(64'd0),.gamma0_updated_state(64'd0),.gamma0_start(),.gamma0_leg_index(),.gamma0_variable_count(),.gamma0_ready(),.gamma0_seed_load(),.gamma0_seed_state(),
  .gamma1_valid(1'b0),.gamma1_variable_index(17'd0),.gamma1_value(5'sd0),.gamma1_done(1'b0),.gamma1_seed_valid(1'b0),.gamma1_seed(64'd1),.gamma1_updated_state(64'd1),.gamma1_start(),.gamma1_leg_index(),.gamma1_variable_count(),.gamma1_ready(),.gamma1_seed_load(),.gamma1_seed_state(),
  .start_accepted(sa),.active_frame_id(af),.engine0_busy(b0),.engine1_busy(b1),.engine0_done(d0),.engine1_done(d1),.engine0_failed(f0),.engine1_failed(f1),.engine0_candidate_valid(c0),.engine1_candidate_valid(c1),.engine0_weight(w0),.engine1_weight(w1),.engine0_iterations(it0),.engine1_iterations(it1),.engine0_legs(l0),.engine1_legs(l1),.global_done(gd),.global_failed(gf),.global_candidate_valid(gcv),.winning_engine_id(win),.winning_weight(),.winning_iteration_count(),.winning_leg_count(),.same_cycle_success(sc),.first_success_cycle(fsc),.winning_frame_id(),.engine0_completion_cycle(dc0),.engine1_completion_cycle(dc1),.correction_req(1'b0),.correction_word(32'd0),.correction_ready,.correction_rsp_valid,.correction_bits,.correction_mask);
 initial begin
  $readmemh("fpga/verification/tier2_p0p003/images/mu_expected_scalar.memh",expected_mu);$readmemh("fpga/verification/tier2_p0p003/images/nu_expected_scalar.memh",expected_nu);$readmemh("fpga/verification/tier2_p0p003/images/marginal_expected_scalar.memh",expected_marg);$readmemh("fpga/verification/tier2_p0p003/images/decision_expected_scalar.memh",expected_dec);
  repeat(2)@(posedge clk);rst=0;@(negedge clk)start=1;@(negedge clk)start=0;wait(d0&&d1);repeat(2)@(posedge clk);#1;fail=0;if(it0!=1||it1!=1||!f0||!f1||dc0!=dc1||dc0==0||!gd||!gf||gcv)$fatal(1,"N2 Tier2 status/overlap/global failure mismatch");
  for(e=0;e<E;e=e+1)begin if($signed(dut.engine_0.memory.mu[e])!==$signed(expected_mu[e])||$signed(dut.engine_1.memory.mu[e])!==$signed(expected_mu[e])||$signed(dut.engine_0.memory.nu[e])!==$signed(expected_nu[e])||$signed(dut.engine_1.memory.nu[e])!==$signed(expected_nu[e]))$fatal(1,"N2 Tier2 edge mismatch %0d",e);end
  for(v=0;v<V;v=v+1)if($signed(dut.engine_0.memory.marg[v])!==$signed(expected_marg[v])||$signed(dut.engine_1.memory.marg[v])!==$signed(expected_marg[v])||dut.engine_0.memory.decision[v]!==expected_dec[v]||dut.engine_1.memory.decision[v]!==expected_dec[v])$fatal(1,"N2 Tier2 node mismatch %0d",v);
  $display("TIER2_N2_ONE_ITERATION_RESULT engines=2 iterations=1 e0_cycles=%0d e1_cycles=%0d elapsed=%0d serialized_sum=%0d failures=%0d",dc0,dc1,dc0,dc0+dc1,fail);$finish;
 end
endmodule
